# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x05route\"\x1e\n\x06IniLoc\x12\x14\n\x0cini_location\x18\x01 \x01(\t\"\x1e\n\x06\x46inLoc\x12\x14\n\x0c\x66in_location\x18\x01 \x01(\t2?\n\nlocalGuide\x12\x31\n\x0bGetLocation\x12\r.route.IniLoc\x1a\r.route.FinLoc\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INILOC._serialized_start=22
  _INILOC._serialized_end=52
  _FINLOC._serialized_start=54
  _FINLOC._serialized_end=84
  _LOCALGUIDE._serialized_start=86
  _LOCALGUIDE._serialized_end=149
# @@protoc_insertion_point(module_scope)
