# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='route.proto',
  package='route',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0broute.proto\x12\x05route\"\x1e\n\x06IniLoc\x12\x14\n\x0cini_location\x18\x01 \x01(\t\"\x1e\n\x06\x46inLoc\x12\x14\n\x0c\x66in_location\x18\x01 \x01(\t\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"Y\n\x11UploadFileRequest\x12#\n\x08metadata\x18\x01 \x01(\x0b\x32\x0f.route.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x82\x01\n\nlocalGuide\x12\x31\n\x0bGetLocation\x12\r.route.IniLoc\x1a\r.route.FinLoc\"\x00(\x01\x30\x01\x12\x41\n\nUploadFile\x12\x18.route.UploadFileRequest\x1a\x15.route.StringResponse\"\x00(\x01\x62\x06proto3'
)




_INILOC = _descriptor.Descriptor(
  name='IniLoc',
  full_name='route.IniLoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ini_location', full_name='route.IniLoc.ini_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_FINLOC = _descriptor.Descriptor(
  name='FinLoc',
  full_name='route.FinLoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fin_location', full_name='route.FinLoc.fin_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=84,
)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='route.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='route.MetaData.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extension', full_name='route.MetaData.extension', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=133,
)


_UPLOADFILEREQUEST = _descriptor.Descriptor(
  name='UploadFileRequest',
  full_name='route.UploadFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='route.UploadFileRequest.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunk_data', full_name='route.UploadFileRequest.chunk_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='route.UploadFileRequest.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=135,
  serialized_end=224,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='route.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='route.StringResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=259,
)

_UPLOADFILEREQUEST.fields_by_name['metadata'].message_type = _METADATA
_UPLOADFILEREQUEST.oneofs_by_name['request'].fields.append(
  _UPLOADFILEREQUEST.fields_by_name['metadata'])
_UPLOADFILEREQUEST.fields_by_name['metadata'].containing_oneof = _UPLOADFILEREQUEST.oneofs_by_name['request']
_UPLOADFILEREQUEST.oneofs_by_name['request'].fields.append(
  _UPLOADFILEREQUEST.fields_by_name['chunk_data'])
_UPLOADFILEREQUEST.fields_by_name['chunk_data'].containing_oneof = _UPLOADFILEREQUEST.oneofs_by_name['request']
DESCRIPTOR.message_types_by_name['IniLoc'] = _INILOC
DESCRIPTOR.message_types_by_name['FinLoc'] = _FINLOC
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['UploadFileRequest'] = _UPLOADFILEREQUEST
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IniLoc = _reflection.GeneratedProtocolMessageType('IniLoc', (_message.Message,), {
  'DESCRIPTOR' : _INILOC,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:route.IniLoc)
  })
_sym_db.RegisterMessage(IniLoc)

FinLoc = _reflection.GeneratedProtocolMessageType('FinLoc', (_message.Message,), {
  'DESCRIPTOR' : _FINLOC,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:route.FinLoc)
  })
_sym_db.RegisterMessage(FinLoc)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:route.MetaData)
  })
_sym_db.RegisterMessage(MetaData)

UploadFileRequest = _reflection.GeneratedProtocolMessageType('UploadFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADFILEREQUEST,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:route.UploadFileRequest)
  })
_sym_db.RegisterMessage(UploadFileRequest)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRINGRESPONSE,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:route.StringResponse)
  })
_sym_db.RegisterMessage(StringResponse)



_LOCALGUIDE = _descriptor.ServiceDescriptor(
  name='localGuide',
  full_name='route.localGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=262,
  serialized_end=392,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLocation',
    full_name='route.localGuide.GetLocation',
    index=0,
    containing_service=None,
    input_type=_INILOC,
    output_type=_FINLOC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UploadFile',
    full_name='route.localGuide.UploadFile',
    index=1,
    containing_service=None,
    input_type=_UPLOADFILEREQUEST,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCALGUIDE)

DESCRIPTOR.services_by_name['localGuide'] = _LOCALGUIDE

# @@protoc_insertion_point(module_scope)
